import { useEffect, useState } from 'react';
const currencies=[['TRY','Türk Lirası','₺'],['USD','Amerikan Doları','$'],['EUR','Euro','€'],['GBP','İngiliz Sterlini','£']];
export default function CurrencySettingsTab({value,onSave}){
 const [form,setForm]=useState(value||{}); useEffect(()=>setForm(value||{}),[value]); const enabled=form.enabled||['TRY'];
 const toggle=(c)=>setForm({...form,enabled:enabled.includes(c)?enabled.filter(x=>x!==c):[...enabled,c]});
 return <div className="bg-card border border-border rounded-xl p-5 space-y-5 max-w-4xl"><div><h2 className="text-lg font-bold">Para Birimleri</h2><p className="text-sm text-muted-foreground">Kabul edilen para birimlerini ve gösterim biçimini belirleyin.</p></div>
 <label className="text-sm font-medium block">Varsayılan Para Birimi<select className="mt-1 w-full sm:w-72 bg-secondary/60 border border-border rounded-lg px-3 py-2" value={form.default||'TRY'} onChange={e=>setForm({...form,default:e.target.value})}>{currencies.map(c=><option key={c[0]} value={c[0]}>{c[1]} ({c[0]})</option>)}</select></label>
 <div className="grid sm:grid-cols-2 gap-3">{currencies.map(([code,name,symbol])=><div key={code} className="flex items-center justify-between border border-border rounded-xl p-4"><div><p className="font-semibold">{symbol} {name}</p><p className="text-xs text-muted-foreground">{code}</p></div><input type="checkbox" checked={enabled.includes(code)} onChange={()=>toggle(code)}/></div>)}</div>
 <div className="grid sm:grid-cols-2 gap-4"><label className="text-sm font-medium">Kur Güncelleme Sıklığı<select className="mt-1 w-full bg-secondary/60 border border-border rounded-lg px-3 py-2" value={form.rate_interval||'daily'} onChange={e=>setForm({...form,rate_interval:e.target.value})}><option value="hourly">Saatlik</option><option value="daily">Günlük</option><option value="manual">Manuel</option></select></label><label className="text-sm font-medium">Fiyat Yuvarlama<select className="mt-1 w-full bg-secondary/60 border border-border rounded-lg px-3 py-2" value={form.rounding||'2'} onChange={e=>setForm({...form,rounding:e.target.value})}><option value="2">2 ondalık</option><option value="0">Tam sayı</option></select></label></div>
 <button onClick={()=>onSave(form)} className="bg-primary text-primary-foreground rounded-lg px-5 py-2 text-sm font-semibold">Para Birimlerini Kaydet</button></div>;
}