import { useRef, useState } from 'react';
import { ChevronRight, Trash2 } from 'lucide-react';
import { Image } from '@/components/ui/image';

export default function ConversationList({ relations, messages, userId, onOpen, onHide, isOnline }) {
  const [swiped, setSwiped] = useState(null); const startX = useRef(0);
  const chats = relations.filter((r) => r.status === 'accepted' && !(r.hidden_for || []).includes(userId)).map((r) => {
    const latest = messages.filter((m) => m.friendship_id === r.id).at(-1);
    return { relation: r, latest };
  }).sort((a, b) => new Date(b.latest?.created_date || b.relation.updated_date) - new Date(a.latest?.created_date || a.relation.updated_date));
  if (!chats.length) return <p className="py-16 text-center text-sm text-muted-foreground">Henüz sohbetiniz yok.</p>;
  return <div>{chats.map(({ relation, latest }) => {
    const mine = relation.requester_id === userId; const name = mine ? relation.recipient_name : relation.requester_name; const avatar = mine ? relation.recipient_avatar : relation.requester_avatar; const unreadCount = messages.filter((m) => m.friendship_id === relation.id && m.recipient_id === userId && !(m.read_by || []).includes(userId)).length;
    return <div key={relation.id} className="relative overflow-hidden border-b border-border"><button onClick={() => onHide(relation)} className="absolute inset-y-0 right-0 w-20 bg-destructive text-destructive-foreground flex flex-col items-center justify-center text-xs font-semibold"><Trash2 className="w-5 h-5 mb-1" /> Sil</button><button onTouchStart={(e) => { startX.current = e.touches[0].clientX; }} onTouchEnd={(e) => setSwiped(startX.current - e.changedTouches[0].clientX > 55 ? relation.id : null)} onClick={() => swiped === relation.id ? setSwiped(null) : onOpen(relation)} className={`relative z-10 w-full flex items-center gap-3 px-4 py-4 text-left transition-transform ${swiped === relation.id ? '-translate-x-20' : 'translate-x-0'} ${unreadCount > 0 ? 'bg-primary/5' : 'bg-background'}`}>
      <div className="relative w-14 h-14 rounded-full bg-secondary shrink-0"><div className="w-full h-full rounded-full overflow-hidden">{avatar ? <Image src={avatar} alt={name} className="w-full h-full" /> : <span className="w-full h-full flex items-center justify-center text-xl font-bold">{name?.[0]}</span>}</div>{unreadCount > 0 && <span className="absolute -top-0.5 -right-0.5 min-w-5 h-5 px-1 rounded-full bg-primary text-primary-foreground text-[10px] font-bold flex items-center justify-center border-2 border-background">{unreadCount}</span>}<span className={`absolute right-0 bottom-0 w-3.5 h-3.5 rounded-full border-2 border-background ${isOnline(relation.requester_id === userId ? relation.recipient_id : relation.requester_id) ? 'bg-green-500' : 'bg-muted-foreground'}`} /></div><div className="min-w-0 flex-1"><p className={`truncate ${unreadCount > 0 ? 'font-bold text-foreground' : 'font-semibold text-muted-foreground'}`}>{name}</p><p className="text-xs text-muted-foreground">{isOnline(relation.requester_id === userId ? relation.recipient_id : relation.requester_id) ? 'Çevrim içi' : 'Çevrim dışı'}</p><p className={`text-sm truncate ${unreadCount > 0 ? 'text-foreground font-medium' : 'text-muted-foreground'}`}>{unreadCount > 0 ? <span className="text-primary">● </span> : ''}{latest?.text || 'Artık arkadaşsınız. Sohbeti başlatın.'}</p></div><div className="text-right shrink-0 flex flex-col items-end gap-1"><p className="text-xs text-muted-foreground">{latest ? new Date(latest.created_date).toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' }) : ''}</p><ChevronRight className="w-4 h-4 ml-auto text-muted-foreground" /></div>
    </button></div>;
  })}</div>;
}